# permissions for end users to view nativequeues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nativequeue-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: native-queue
    app.kubernetes.io/part-of: native-queue
    app.kubernetes.io/managed-by: kustomize
  name: nativequeue-viewer-role
rules:
- apiGroups:
  - iskprinter.com
  resources:
  - nativequeues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iskprinter.com
  resources:
  - nativequeues/status
  verbs:
  - get
